[package]
name = "helm-r2g"
version = "0.1.0"
edition = "2024"
license = "MIT/Apache-2.0"
publish = false
include = ["/src", "/go"]

[dependencies]
rust2go = { version = "0.4.1" }

[build-dependencies]
rust2go = { version = "0.4.1", features = ["build"] }
