package main

/*
// Generated by rust2go. Please DO NOT edit this C part manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct StringRef {
  const uint8_t *ptr;
  uintptr_t len;
} StringRef;

typedef struct ListRef {
  const void *ptr;
  uintptr_t len;
} ListRef;

typedef struct HelmEnvRef {
  struct ListRef kube_config;
  struct ListRef kube_context;
  struct ListRef kube_token;
  struct ListRef kube_ca_file;
  bool kube_insecure_skip_tls_verify;
} HelmEnvRef;

typedef struct HelmChartInstallRequestRef {
  struct StringRef release_name;
  struct StringRef chart;
  struct StringRef version;
  struct StringRef ns;
  bool wait;
  struct ListRef timeout;
  bool create_namespace;
  struct ListRef values;
  struct HelmEnvRef env;
  struct ListRef dry_run;
} HelmChartInstallRequestRef;

typedef struct HelmChartInstallResponseRef {
  struct ListRef err;
  struct StringRef data;
} HelmChartInstallResponseRef;

typedef struct HelmChartListRequestRef {
  struct StringRef ns;
  struct HelmEnvRef env;
  bool all;
  bool all_namespaces;
  uint64_t sort;
  bool by_date;
  bool sort_reverse;
  uint64_t state_mask;
  int64_t limit;
  int64_t offset;
  struct StringRef filter;
  bool no_headers;
  struct StringRef time_format;
  bool uninstalled;
  bool superseded;
  bool uninstalling;
  bool deployed;
  bool failed;
  bool pending;
  struct StringRef selector;
} HelmChartListRequestRef;

typedef struct HelmChartListResponseRef {
  struct ListRef err;
  struct StringRef data;
} HelmChartListResponseRef;

typedef struct HelmChartSearchRequestRef {
  bool versions;
  struct StringRef regexp;
  bool devel;
  struct StringRef version;
  struct ListRef terms;
  struct HelmEnvRef env;
} HelmChartSearchRequestRef;

typedef struct HelmChartSearchResponseRef {
  struct ListRef err;
  struct StringRef data;
} HelmChartSearchResponseRef;

typedef struct HelmChartUpgradeRequestRef {
  struct StringRef release_name;
  struct StringRef chart;
  struct StringRef version;
  struct StringRef ns;
  bool wait;
  struct ListRef timeout;
  struct ListRef values;
  struct HelmEnvRef env;
  bool reset_values;
  bool reuse_values;
  struct ListRef dry_run;
} HelmChartUpgradeRequestRef;

typedef struct HelmChartUpgradeResponseRef {
  struct ListRef err;
  struct StringRef data;
} HelmChartUpgradeResponseRef;
*/
import "C"
import (
	"runtime"
	"unsafe"

	"github.com/ihciah/rust2go/asmcall"
)

var HelmCallImpl HelmCall

type HelmCall interface {
	install(req *HelmChartInstallRequest) HelmChartInstallResponse
	upgrade(req *HelmChartUpgradeRequest) HelmChartUpgradeResponse
	list(req *HelmChartListRequest) HelmChartListResponse
	repo_search(req *HelmChartSearchRequest) HelmChartSearchResponse
}

//export CHelmCall_install
func CHelmCall_install(req C.HelmChartInstallRequestRef, slot *C.void, cb *C.void) {
	_new_req := newHelmChartInstallRequest(req)
	go func() {
		resp := HelmCallImpl.install(&_new_req)
		resp_ref, buffer := cvt_ref(cntHelmChartInstallResponse, refHelmChartInstallResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CHelmCall_upgrade
func CHelmCall_upgrade(req C.HelmChartUpgradeRequestRef, slot *C.void, cb *C.void) {
	_new_req := newHelmChartUpgradeRequest(req)
	go func() {
		resp := HelmCallImpl.upgrade(&_new_req)
		resp_ref, buffer := cvt_ref(cntHelmChartUpgradeResponse, refHelmChartUpgradeResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CHelmCall_list
func CHelmCall_list(req C.HelmChartListRequestRef, slot *C.void, cb *C.void) {
	_new_req := newHelmChartListRequest(req)
	go func() {
		resp := HelmCallImpl.list(&_new_req)
		resp_ref, buffer := cvt_ref(cntHelmChartListResponse, refHelmChartListResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CHelmCall_repo_search
func CHelmCall_repo_search(req C.HelmChartSearchRequestRef, slot *C.void, cb *C.void) {
	_new_req := newHelmChartSearchRequest(req)
	go func() {
		resp := HelmCallImpl.repo_search(&_new_req)
		resp_ref, buffer := cvt_ref(cntHelmChartSearchResponse, refHelmChartSearchResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

func newString(s_ref C.StringRef) string {
	return unsafe.String((*byte)(unsafe.Pointer(s_ref.ptr)), s_ref.len)
}
func refString(s *string, _ *[]byte) C.StringRef {
	return C.StringRef{
		ptr: (*C.uint8_t)(unsafe.StringData(*s)),
		len: C.uintptr_t(len(*s)),
	}
}

func ownString(s_ref C.StringRef) string {
	return string(unsafe.Slice((*byte)(unsafe.Pointer(s_ref.ptr)), int(s_ref.len)))
}
func cntString(_ *string, _ *uint) [0]C.StringRef { return [0]C.StringRef{} }
func new_list_mapper[T1, T2 any](f func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		input := unsafe.Slice((*T1)(unsafe.Pointer(x.ptr)), x.len)
		output := make([]T2, len(input))
		for i, v := range input {
			output[i] = f(v)
		}
		return output
	}
}
func new_list_mapper_primitive[T1, T2 any](_ func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		return unsafe.Slice((*T2)(unsafe.Pointer(x.ptr)), x.len)
	}
}

// only handle non-primitive type T
func cnt_list_mapper[T, R any](f func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef {
		for _, v := range *s {
			f(&v, cnt)
		}
		*cnt += uint(len(*s)) * size_of[R]()
		return [0]C.ListRef{}
	}
}

// only handle primitive type T
func cnt_list_mapper_primitive[T, R any](_ func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef { return [0]C.ListRef{} }
}

// only handle non-primitive type T
func ref_list_mapper[T, R any](f func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*buffer) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(len(*s)),
			}
		}
		ret := C.ListRef{
			ptr: unsafe.Pointer(&(*buffer)[0]),
			len: C.uintptr_t(len(*s)),
		}
		children_bytes := int(size_of[R]()) * len(*s)
		children := (*buffer)[:children_bytes]
		*buffer = (*buffer)[children_bytes:]
		for _, v := range *s {
			child := f(&v, buffer)
			len := unsafe.Sizeof(child)
			copy(children, unsafe.Slice((*byte)(unsafe.Pointer(&child)), len))
			children = children[len:]
		}
		return ret
	}
}

// only handle primitive type T
func ref_list_mapper_primitive[T, R any](_ func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*s) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(0),
			}
		}
		return C.ListRef{
			ptr: unsafe.Pointer(&(*s)[0]),
			len: C.uintptr_t(len(*s)),
		}
	}
}
func size_of[T any]() uint {
	var t T
	return uint(unsafe.Sizeof(t))
}
func cvt_ref[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		buffer := make([]byte, cnt)
		return ref_f(p, &buffer), buffer
	}
}
func cvt_ref_cap[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR, add_cap uint) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		buffer := make([]byte, cnt, cnt+add_cap)
		return ref_f(p, &buffer), buffer
	}
}

func newC_uint8_t(n C.uint8_t) uint8    { return uint8(n) }
func newC_uint16_t(n C.uint16_t) uint16 { return uint16(n) }
func newC_uint32_t(n C.uint32_t) uint32 { return uint32(n) }
func newC_uint64_t(n C.uint64_t) uint64 { return uint64(n) }
func newC_int8_t(n C.int8_t) int8       { return int8(n) }
func newC_int16_t(n C.int16_t) int16    { return int16(n) }
func newC_int32_t(n C.int32_t) int32    { return int32(n) }
func newC_int64_t(n C.int64_t) int64    { return int64(n) }
func newC_bool(n C.bool) bool           { return bool(n) }
func newC_uintptr_t(n C.uintptr_t) uint { return uint(n) }
func newC_intptr_t(n C.intptr_t) int    { return int(n) }
func newC_float(n C.float) float32      { return float32(n) }
func newC_double(n C.double) float64    { return float64(n) }

func cntC_uint8_t(_ *uint8, _ *uint) [0]C.uint8_t    { return [0]C.uint8_t{} }
func cntC_uint16_t(_ *uint16, _ *uint) [0]C.uint16_t { return [0]C.uint16_t{} }
func cntC_uint32_t(_ *uint32, _ *uint) [0]C.uint32_t { return [0]C.uint32_t{} }
func cntC_uint64_t(_ *uint64, _ *uint) [0]C.uint64_t { return [0]C.uint64_t{} }
func cntC_int8_t(_ *int8, _ *uint) [0]C.int8_t       { return [0]C.int8_t{} }
func cntC_int16_t(_ *int16, _ *uint) [0]C.int16_t    { return [0]C.int16_t{} }
func cntC_int32_t(_ *int32, _ *uint) [0]C.int32_t    { return [0]C.int32_t{} }
func cntC_int64_t(_ *int64, _ *uint) [0]C.int64_t    { return [0]C.int64_t{} }
func cntC_bool(_ *bool, _ *uint) [0]C.bool           { return [0]C.bool{} }
func cntC_uintptr_t(_ *uint, _ *uint) [0]C.uintptr_t { return [0]C.uintptr_t{} }
func cntC_intptr_t(_ *int, _ *uint) [0]C.intptr_t    { return [0]C.intptr_t{} }
func cntC_float(_ *float32, _ *uint) [0]C.float      { return [0]C.float{} }
func cntC_double(_ *float64, _ *uint) [0]C.double    { return [0]C.double{} }

func refC_uint8_t(p *uint8, _ *[]byte) C.uint8_t    { return C.uint8_t(*p) }
func refC_uint16_t(p *uint16, _ *[]byte) C.uint16_t { return C.uint16_t(*p) }
func refC_uint32_t(p *uint32, _ *[]byte) C.uint32_t { return C.uint32_t(*p) }
func refC_uint64_t(p *uint64, _ *[]byte) C.uint64_t { return C.uint64_t(*p) }
func refC_int8_t(p *int8, _ *[]byte) C.int8_t       { return C.int8_t(*p) }
func refC_int16_t(p *int16, _ *[]byte) C.int16_t    { return C.int16_t(*p) }
func refC_int32_t(p *int32, _ *[]byte) C.int32_t    { return C.int32_t(*p) }
func refC_int64_t(p *int64, _ *[]byte) C.int64_t    { return C.int64_t(*p) }
func refC_bool(p *bool, _ *[]byte) C.bool           { return C.bool(*p) }
func refC_uintptr_t(p *uint, _ *[]byte) C.uintptr_t { return C.uintptr_t(*p) }
func refC_intptr_t(p *int, _ *[]byte) C.intptr_t    { return C.intptr_t(*p) }
func refC_float(p *float32, _ *[]byte) C.float      { return C.float(*p) }
func refC_double(p *float64, _ *[]byte) C.double    { return C.double(*p) }

type HelmChartInstallRequest struct {
	release_name     string
	chart            string
	version          string
	ns               string
	wait             bool
	timeout          []int64
	create_namespace bool
	values           []uint8
	env              HelmEnv
	dry_run          []string
}

func newHelmChartInstallRequest(p C.HelmChartInstallRequestRef) HelmChartInstallRequest {
	return HelmChartInstallRequest{
		release_name:     newString(p.release_name),
		chart:            newString(p.chart),
		version:          newString(p.version),
		ns:               newString(p.ns),
		wait:             newC_bool(p.wait),
		timeout:          new_list_mapper_primitive(newC_int64_t)(p.timeout),
		create_namespace: newC_bool(p.create_namespace),
		values:           new_list_mapper_primitive(newC_uint8_t)(p.values),
		env:              newHelmEnv(p.env),
		dry_run:          new_list_mapper(newString)(p.dry_run),
	}
}
func ownHelmChartInstallRequest(p C.HelmChartInstallRequestRef) HelmChartInstallRequest {
	return HelmChartInstallRequest{
		release_name:     ownString(p.release_name),
		chart:            ownString(p.chart),
		version:          ownString(p.version),
		ns:               ownString(p.ns),
		wait:             newC_bool(p.wait),
		timeout:          new_list_mapper(newC_int64_t)(p.timeout),
		create_namespace: newC_bool(p.create_namespace),
		values:           new_list_mapper(newC_uint8_t)(p.values),
		env:              ownHelmEnv(p.env),
		dry_run:          new_list_mapper(ownString)(p.dry_run),
	}
}
func cntHelmChartInstallRequest(s *HelmChartInstallRequest, cnt *uint) [0]C.HelmChartInstallRequestRef {
	cntHelmEnv(&s.env, cnt)
	cnt_list_mapper(cntString)(&s.dry_run, cnt)
	return [0]C.HelmChartInstallRequestRef{}
}
func refHelmChartInstallRequest(p *HelmChartInstallRequest, buffer *[]byte) C.HelmChartInstallRequestRef {
	return C.HelmChartInstallRequestRef{
		release_name:     refString(&p.release_name, buffer),
		chart:            refString(&p.chart, buffer),
		version:          refString(&p.version, buffer),
		ns:               refString(&p.ns, buffer),
		wait:             refC_bool(&p.wait, buffer),
		timeout:          ref_list_mapper_primitive(refC_int64_t)(&p.timeout, buffer),
		create_namespace: refC_bool(&p.create_namespace, buffer),
		values:           ref_list_mapper_primitive(refC_uint8_t)(&p.values, buffer),
		env:              refHelmEnv(&p.env, buffer),
		dry_run:          ref_list_mapper(refString)(&p.dry_run, buffer),
	}
}

type HelmChartUpgradeRequest struct {
	release_name string
	chart        string
	version      string
	ns           string
	wait         bool
	timeout      []int64
	values       []uint8
	env          HelmEnv
	reset_values bool
	reuse_values bool
	dry_run      []string
}

func newHelmChartUpgradeRequest(p C.HelmChartUpgradeRequestRef) HelmChartUpgradeRequest {
	return HelmChartUpgradeRequest{
		release_name: newString(p.release_name),
		chart:        newString(p.chart),
		version:      newString(p.version),
		ns:           newString(p.ns),
		wait:         newC_bool(p.wait),
		timeout:      new_list_mapper_primitive(newC_int64_t)(p.timeout),
		values:       new_list_mapper_primitive(newC_uint8_t)(p.values),
		env:          newHelmEnv(p.env),
		reset_values: newC_bool(p.reset_values),
		reuse_values: newC_bool(p.reuse_values),
		dry_run:      new_list_mapper(newString)(p.dry_run),
	}
}
func ownHelmChartUpgradeRequest(p C.HelmChartUpgradeRequestRef) HelmChartUpgradeRequest {
	return HelmChartUpgradeRequest{
		release_name: ownString(p.release_name),
		chart:        ownString(p.chart),
		version:      ownString(p.version),
		ns:           ownString(p.ns),
		wait:         newC_bool(p.wait),
		timeout:      new_list_mapper(newC_int64_t)(p.timeout),
		values:       new_list_mapper(newC_uint8_t)(p.values),
		env:          ownHelmEnv(p.env),
		reset_values: newC_bool(p.reset_values),
		reuse_values: newC_bool(p.reuse_values),
		dry_run:      new_list_mapper(ownString)(p.dry_run),
	}
}
func cntHelmChartUpgradeRequest(s *HelmChartUpgradeRequest, cnt *uint) [0]C.HelmChartUpgradeRequestRef {
	cntHelmEnv(&s.env, cnt)
	cnt_list_mapper(cntString)(&s.dry_run, cnt)
	return [0]C.HelmChartUpgradeRequestRef{}
}
func refHelmChartUpgradeRequest(p *HelmChartUpgradeRequest, buffer *[]byte) C.HelmChartUpgradeRequestRef {
	return C.HelmChartUpgradeRequestRef{
		release_name: refString(&p.release_name, buffer),
		chart:        refString(&p.chart, buffer),
		version:      refString(&p.version, buffer),
		ns:           refString(&p.ns, buffer),
		wait:         refC_bool(&p.wait, buffer),
		timeout:      ref_list_mapper_primitive(refC_int64_t)(&p.timeout, buffer),
		values:       ref_list_mapper_primitive(refC_uint8_t)(&p.values, buffer),
		env:          refHelmEnv(&p.env, buffer),
		reset_values: refC_bool(&p.reset_values, buffer),
		reuse_values: refC_bool(&p.reuse_values, buffer),
		dry_run:      ref_list_mapper(refString)(&p.dry_run, buffer),
	}
}

type HelmEnv struct {
	kube_config                   []string
	kube_context                  []string
	kube_token                    []string
	kube_ca_file                  []string
	kube_insecure_skip_tls_verify bool
}

func newHelmEnv(p C.HelmEnvRef) HelmEnv {
	return HelmEnv{
		kube_config:                   new_list_mapper(newString)(p.kube_config),
		kube_context:                  new_list_mapper(newString)(p.kube_context),
		kube_token:                    new_list_mapper(newString)(p.kube_token),
		kube_ca_file:                  new_list_mapper(newString)(p.kube_ca_file),
		kube_insecure_skip_tls_verify: newC_bool(p.kube_insecure_skip_tls_verify),
	}
}
func ownHelmEnv(p C.HelmEnvRef) HelmEnv {
	return HelmEnv{
		kube_config:                   new_list_mapper(ownString)(p.kube_config),
		kube_context:                  new_list_mapper(ownString)(p.kube_context),
		kube_token:                    new_list_mapper(ownString)(p.kube_token),
		kube_ca_file:                  new_list_mapper(ownString)(p.kube_ca_file),
		kube_insecure_skip_tls_verify: newC_bool(p.kube_insecure_skip_tls_verify),
	}
}
func cntHelmEnv(s *HelmEnv, cnt *uint) [0]C.HelmEnvRef {
	cnt_list_mapper(cntString)(&s.kube_config, cnt)
	cnt_list_mapper(cntString)(&s.kube_context, cnt)
	cnt_list_mapper(cntString)(&s.kube_token, cnt)
	cnt_list_mapper(cntString)(&s.kube_ca_file, cnt)
	return [0]C.HelmEnvRef{}
}
func refHelmEnv(p *HelmEnv, buffer *[]byte) C.HelmEnvRef {
	return C.HelmEnvRef{
		kube_config:                   ref_list_mapper(refString)(&p.kube_config, buffer),
		kube_context:                  ref_list_mapper(refString)(&p.kube_context, buffer),
		kube_token:                    ref_list_mapper(refString)(&p.kube_token, buffer),
		kube_ca_file:                  ref_list_mapper(refString)(&p.kube_ca_file, buffer),
		kube_insecure_skip_tls_verify: refC_bool(&p.kube_insecure_skip_tls_verify, buffer),
	}
}

type HelmChartInstallResponse struct {
	err  []string
	data string
}

func newHelmChartInstallResponse(p C.HelmChartInstallResponseRef) HelmChartInstallResponse {
	return HelmChartInstallResponse{
		err:  new_list_mapper(newString)(p.err),
		data: newString(p.data),
	}
}
func ownHelmChartInstallResponse(p C.HelmChartInstallResponseRef) HelmChartInstallResponse {
	return HelmChartInstallResponse{
		err:  new_list_mapper(ownString)(p.err),
		data: ownString(p.data),
	}
}
func cntHelmChartInstallResponse(s *HelmChartInstallResponse, cnt *uint) [0]C.HelmChartInstallResponseRef {
	cnt_list_mapper(cntString)(&s.err, cnt)
	return [0]C.HelmChartInstallResponseRef{}
}
func refHelmChartInstallResponse(p *HelmChartInstallResponse, buffer *[]byte) C.HelmChartInstallResponseRef {
	return C.HelmChartInstallResponseRef{
		err:  ref_list_mapper(refString)(&p.err, buffer),
		data: refString(&p.data, buffer),
	}
}

type HelmChartUpgradeResponse struct {
	err  []string
	data string
}

func newHelmChartUpgradeResponse(p C.HelmChartUpgradeResponseRef) HelmChartUpgradeResponse {
	return HelmChartUpgradeResponse{
		err:  new_list_mapper(newString)(p.err),
		data: newString(p.data),
	}
}
func ownHelmChartUpgradeResponse(p C.HelmChartUpgradeResponseRef) HelmChartUpgradeResponse {
	return HelmChartUpgradeResponse{
		err:  new_list_mapper(ownString)(p.err),
		data: ownString(p.data),
	}
}
func cntHelmChartUpgradeResponse(s *HelmChartUpgradeResponse, cnt *uint) [0]C.HelmChartUpgradeResponseRef {
	cnt_list_mapper(cntString)(&s.err, cnt)
	return [0]C.HelmChartUpgradeResponseRef{}
}
func refHelmChartUpgradeResponse(p *HelmChartUpgradeResponse, buffer *[]byte) C.HelmChartUpgradeResponseRef {
	return C.HelmChartUpgradeResponseRef{
		err:  ref_list_mapper(refString)(&p.err, buffer),
		data: refString(&p.data, buffer),
	}
}

type HelmChartListRequest struct {
	ns             string
	env            HelmEnv
	all            bool
	all_namespaces bool
	sort           uint64
	by_date        bool
	sort_reverse   bool
	state_mask     uint64
	limit          int64
	offset         int64
	filter         string
	no_headers     bool
	time_format    string
	uninstalled    bool
	superseded     bool
	uninstalling   bool
	deployed       bool
	failed         bool
	pending        bool
	selector       string
}

func newHelmChartListRequest(p C.HelmChartListRequestRef) HelmChartListRequest {
	return HelmChartListRequest{
		ns:             newString(p.ns),
		env:            newHelmEnv(p.env),
		all:            newC_bool(p.all),
		all_namespaces: newC_bool(p.all_namespaces),
		sort:           newC_uint64_t(p.sort),
		by_date:        newC_bool(p.by_date),
		sort_reverse:   newC_bool(p.sort_reverse),
		state_mask:     newC_uint64_t(p.state_mask),
		limit:          newC_int64_t(p.limit),
		offset:         newC_int64_t(p.offset),
		filter:         newString(p.filter),
		no_headers:     newC_bool(p.no_headers),
		time_format:    newString(p.time_format),
		uninstalled:    newC_bool(p.uninstalled),
		superseded:     newC_bool(p.superseded),
		uninstalling:   newC_bool(p.uninstalling),
		deployed:       newC_bool(p.deployed),
		failed:         newC_bool(p.failed),
		pending:        newC_bool(p.pending),
		selector:       newString(p.selector),
	}
}
func ownHelmChartListRequest(p C.HelmChartListRequestRef) HelmChartListRequest {
	return HelmChartListRequest{
		ns:             ownString(p.ns),
		env:            ownHelmEnv(p.env),
		all:            newC_bool(p.all),
		all_namespaces: newC_bool(p.all_namespaces),
		sort:           newC_uint64_t(p.sort),
		by_date:        newC_bool(p.by_date),
		sort_reverse:   newC_bool(p.sort_reverse),
		state_mask:     newC_uint64_t(p.state_mask),
		limit:          newC_int64_t(p.limit),
		offset:         newC_int64_t(p.offset),
		filter:         ownString(p.filter),
		no_headers:     newC_bool(p.no_headers),
		time_format:    ownString(p.time_format),
		uninstalled:    newC_bool(p.uninstalled),
		superseded:     newC_bool(p.superseded),
		uninstalling:   newC_bool(p.uninstalling),
		deployed:       newC_bool(p.deployed),
		failed:         newC_bool(p.failed),
		pending:        newC_bool(p.pending),
		selector:       ownString(p.selector),
	}
}
func cntHelmChartListRequest(s *HelmChartListRequest, cnt *uint) [0]C.HelmChartListRequestRef {
	cntHelmEnv(&s.env, cnt)
	return [0]C.HelmChartListRequestRef{}
}
func refHelmChartListRequest(p *HelmChartListRequest, buffer *[]byte) C.HelmChartListRequestRef {
	return C.HelmChartListRequestRef{
		ns:             refString(&p.ns, buffer),
		env:            refHelmEnv(&p.env, buffer),
		all:            refC_bool(&p.all, buffer),
		all_namespaces: refC_bool(&p.all_namespaces, buffer),
		sort:           refC_uint64_t(&p.sort, buffer),
		by_date:        refC_bool(&p.by_date, buffer),
		sort_reverse:   refC_bool(&p.sort_reverse, buffer),
		state_mask:     refC_uint64_t(&p.state_mask, buffer),
		limit:          refC_int64_t(&p.limit, buffer),
		offset:         refC_int64_t(&p.offset, buffer),
		filter:         refString(&p.filter, buffer),
		no_headers:     refC_bool(&p.no_headers, buffer),
		time_format:    refString(&p.time_format, buffer),
		uninstalled:    refC_bool(&p.uninstalled, buffer),
		superseded:     refC_bool(&p.superseded, buffer),
		uninstalling:   refC_bool(&p.uninstalling, buffer),
		deployed:       refC_bool(&p.deployed, buffer),
		failed:         refC_bool(&p.failed, buffer),
		pending:        refC_bool(&p.pending, buffer),
		selector:       refString(&p.selector, buffer),
	}
}

type HelmChartListResponse struct {
	err  []string
	data string
}

func newHelmChartListResponse(p C.HelmChartListResponseRef) HelmChartListResponse {
	return HelmChartListResponse{
		err:  new_list_mapper(newString)(p.err),
		data: newString(p.data),
	}
}
func ownHelmChartListResponse(p C.HelmChartListResponseRef) HelmChartListResponse {
	return HelmChartListResponse{
		err:  new_list_mapper(ownString)(p.err),
		data: ownString(p.data),
	}
}
func cntHelmChartListResponse(s *HelmChartListResponse, cnt *uint) [0]C.HelmChartListResponseRef {
	cnt_list_mapper(cntString)(&s.err, cnt)
	return [0]C.HelmChartListResponseRef{}
}
func refHelmChartListResponse(p *HelmChartListResponse, buffer *[]byte) C.HelmChartListResponseRef {
	return C.HelmChartListResponseRef{
		err:  ref_list_mapper(refString)(&p.err, buffer),
		data: refString(&p.data, buffer),
	}
}

type HelmChartSearchRequest struct {
	versions bool
	regexp   string
	devel    bool
	version  string
	terms    []string
	env      HelmEnv
}

func newHelmChartSearchRequest(p C.HelmChartSearchRequestRef) HelmChartSearchRequest {
	return HelmChartSearchRequest{
		versions: newC_bool(p.versions),
		regexp:   newString(p.regexp),
		devel:    newC_bool(p.devel),
		version:  newString(p.version),
		terms:    new_list_mapper(newString)(p.terms),
		env:      newHelmEnv(p.env),
	}
}
func ownHelmChartSearchRequest(p C.HelmChartSearchRequestRef) HelmChartSearchRequest {
	return HelmChartSearchRequest{
		versions: newC_bool(p.versions),
		regexp:   ownString(p.regexp),
		devel:    newC_bool(p.devel),
		version:  ownString(p.version),
		terms:    new_list_mapper(ownString)(p.terms),
		env:      ownHelmEnv(p.env),
	}
}
func cntHelmChartSearchRequest(s *HelmChartSearchRequest, cnt *uint) [0]C.HelmChartSearchRequestRef {
	cnt_list_mapper(cntString)(&s.terms, cnt)
	cntHelmEnv(&s.env, cnt)
	return [0]C.HelmChartSearchRequestRef{}
}
func refHelmChartSearchRequest(p *HelmChartSearchRequest, buffer *[]byte) C.HelmChartSearchRequestRef {
	return C.HelmChartSearchRequestRef{
		versions: refC_bool(&p.versions, buffer),
		regexp:   refString(&p.regexp, buffer),
		devel:    refC_bool(&p.devel, buffer),
		version:  refString(&p.version, buffer),
		terms:    ref_list_mapper(refString)(&p.terms, buffer),
		env:      refHelmEnv(&p.env, buffer),
	}
}

type HelmChartSearchResponse struct {
	err  []string
	data string
}

func newHelmChartSearchResponse(p C.HelmChartSearchResponseRef) HelmChartSearchResponse {
	return HelmChartSearchResponse{
		err:  new_list_mapper(newString)(p.err),
		data: newString(p.data),
	}
}
func ownHelmChartSearchResponse(p C.HelmChartSearchResponseRef) HelmChartSearchResponse {
	return HelmChartSearchResponse{
		err:  new_list_mapper(ownString)(p.err),
		data: ownString(p.data),
	}
}
func cntHelmChartSearchResponse(s *HelmChartSearchResponse, cnt *uint) [0]C.HelmChartSearchResponseRef {
	cnt_list_mapper(cntString)(&s.err, cnt)
	return [0]C.HelmChartSearchResponseRef{}
}
func refHelmChartSearchResponse(p *HelmChartSearchResponse, buffer *[]byte) C.HelmChartSearchResponseRef {
	return C.HelmChartSearchResponseRef{
		err:  ref_list_mapper(refString)(&p.err, buffer),
		data: refString(&p.data, buffer),
	}
}
func main() {}
